<a href="https://colab.research.google.com/github/sattvikkk/naive_bayes/blob/main/Naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
data = pd.read_csv("spam.tsv",sep='\t',names=['Class','Message'])
data

     Class                                            Message
0      ham  I've been searching for the right words to tha...
1     spam  Free entry in 2 a wkly comp to win FA Cup fina...
2      ham  Nah I don't think he goes to usf, he lives aro...
3      ham  Even my brother is not like to speak with me. ...
4      ham               I HAVE A DATE ON SUNDAY WITH WILL!!!
...    ...                                                ...
5562  spam  This is the 2nd time we have tried 2 contact u...
5563   ham               Will ü b going to esplanade fr home?
5564   ham  Pity, * was in mood for that. So...any other s...
5565   ham  The guy did some bitching but I acted like i'd...
5566   ham                         Rofl. Its true to its name

[5567 rows x 2 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5567 entries, 0 to 5566
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Class    5567 non-null   object
 1   Message  5567 non-null   object
dtypes: object(2)
memory usage: 87.1+ KB

In [ ]:
data['Length'] = data['Message'].apply(len)

In [ ]:
data.head(10)

  Class                                            Message  Length
0   ham  I've been searching for the right words to tha...     196
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
2   ham  Nah I don't think he goes to usf, he lives aro...      61
3   ham  Even my brother is not like to speak with me. ...      77
4   ham               I HAVE A DATE ON SUNDAY WITH WILL!!!      36
5   ham  As per your request 'Melle Melle (Oru Minnamin...     160
6  spam  WINNER!! As a valued network customer you have...     157
7  spam  Had your mobile 11 months or more? U R entitle...     154
8   ham  I'm gonna be home soon and i don't want to tal...     109
9  spam  SIX chances to win CASH! From 100 to 20,000 po...     136

In [ ]:
data.groupby('Class').count()

       Message  Length
Class
ham       4821    4821
spam       746     746

In [ ]:
data['Length'].describe()

count    5567.000000
mean       80.450153
std        59.891023
min         2.000000
25%        36.000000
50%        62.000000
75%       122.000000
max       910.000000
Name: Length, dtype: float64

In [ ]:
data[data['Length']==910]['Message'].iloc[0]

"For me the love should start with attraction.i should feel that I need her every time around me.she should be the first thing which comes in my thoughts.I would start the day and end it with her.she should be there every time I dream.love will be then when my every breath has her name.my life should happen around her.my life will be named to her.I would cry for her.will give all my happiness and take all her sorrows.I will be ready to fight with anyone for her.I will be in love when I will be doing the craziest things for her.love will be when I don't have to proove anyone that my girl is the most beautiful lady on the whole planet.I will always be singing praises for her.love will be when I start up making chicken curry and end up makiing sambar.life will be the most beautiful then.will get every morning and thank god for the day because she is with me.I would like to say a lot..will tell later.."

In [ ]:
data[data['Length']==2]['Message'].iloc[0]

'Ok'

In [ ]:
dObject = data['Class'].values
dObject

array(['ham', 'spam', 'ham', ..., 'ham', 'ham', 'ham'], dtype=object)

In [ ]:
data['Target']=data['Class'].map({'ham':0,'spam':1})

In [ ]:
data.loc[data['Class']=="ham",'Class'] = 1
data.loc[data['Class']=="spam",'Class'] = 0

In [ ]:
dObject2=data.Class.values
dObject2

array([1, 0, 1, ..., 1, 1, 1], dtype=object)

In [ ]:
data.head(8)

  Class                                            Message  Length  Target
0     1  I've been searching for the right words to tha...     196       0
1     0  Free entry in 2 a wkly comp to win FA Cup fina...     155       1
2     1  Nah I don't think he goes to usf, he lives aro...      61       0
3     1  Even my brother is not like to speak with me. ...      77       0
4     1               I HAVE A DATE ON SUNDAY WITH WILL!!!      36       0
5     1  As per your request 'Melle Melle (Oru Minnamin...     160       0
6     0  WINNER!! As a valued network customer you have...     157       1
7     0  Had your mobile 11 months or more? U R entitle...     154       1

In [ ]:
import string

string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
l1=['a','b','c']
"*".join(l1)

'a*b*c'

In [ ]:
str1=data['Message'][0]

In [ ]:
[i for i in str1 if i not in string.punctuation]

['I',
 'v',
 'e',
 ' ',
 'b',
 'e',
 'e',
 'n',
 ' ',
 's',
 'e',
 'a',
 'r',
 'c',
 'h',
 'i',
 'n',
 'g',
 ' ',
 'f',
 'o',
 'r',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'r',
 'i',
 'g',
 'h',
 't',
 ' ',
 'w',
 'o',
 'r',
 'd',
 's',
 ' ',
 't',
 'o',
 ' ',
 't',
 'h',
 'a',
 'n',
 'k',
 ' ',
 'y',
 'o',
 'u',
 ' ',
 'f',
 'o',
 'r',
 ' ',
 't',
 'h',
 'i',
 's',
 ' ',
 'b',
 'r',
 'e',
 'a',
 't',
 'h',
 'e',
 'r',
 ' ',
 'I',
 ' ',
 'p',
 'r',
 'o',
 'm',
 'i',
 's',
 'e',
 ' ',
 'i',
 ' ',
 'w',
 'o',
 'n',
 't',
 ' ',
 't',
 'a',
 'k',
 'e',
 ' ',
 'y',
 'o',
 'u',
 'r',
 ' ',
 'h',
 'e',
 'l',
 'p',
 ' ',
 'f',
 'o',
 'r',
 ' ',
 'g',
 'r',
 'a',
 'n',
 't',
 'e',
 'd',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'w',
 'i',
 'l',
 'l',
 ' ',
 'f',
 'u',
 'l',
 'f',
 'i',
 'l',
 ' ',
 'm',
 'y',
 ' ',
 'p',
 'r',
 'o',
 'm',
 'i',
 's',
 'e',
 ' ',
 'Y',
 'o',
 'u',
 ' ',
 'h',
 'a',
 'v',
 'e',
 ' ',
 'b',
 'e',
 'e',
 'n',
 ' ',
 'w',
 'o',
 'n',
 'd',
 'e',
 'r',
 'f',
 'u',
 'l',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 'a',
 ' ',
 'b',
 'l',
 'e',
 's',
 's',
 'i',
 'n',
 'g',
 ' ',
 'a',
 't',
 ' ',
 'a',
 'l',
 'l',
 ' ',
 't',
 'i',
 'm',
 'e',
 's']

In [ ]:
def remove(text):
  out=''
  for i in text:
    if i not in string.punctuation:
      out+=i
  return out

In [ ]:
l1=[]
for i in str1:
  if i not in string.punctuation:
    l1.append(i)

In [ ]:
"".join(l1)

'Ive been searching for the right words to thank you for this breather I promise i wont take your help for granted and will fulfil my promise You have been wonderful and a blessing at all times'

In [ ]:
def remove_punc(text):
  text="".join([char for char in text if char not in string.punctuation])
  return text.lower()

data['text_clean'] = data['Message'].apply(lambda x:remove_punc(x))
data.head()

,Class,Message,Length,Target,text_clean
0,1,I've been searching for the right words to tha...,196,0,ive been searching for the right words to than...
1,0,Free entry in 2 a wkly comp to win FA Cup fina...,155,1,free entry in 2 a wkly comp to win fa cup fina...
2,1,"Nah I don't think he goes to usf, he lives aro...",61,0,nah i dont think he goes to usf he lives aroun...
3,1,Even my brother is not like to speak with me. ...,77,0,even my brother is not like to speak with me t...
4,1,I HAVE A DATE ON SUNDAY WITH WILL!!!,36,0,i have a date on sunday with will

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
CV = CountVectorizer(stop_words="english")

In [ ]:
CV.fit(data['text_clean'])

CountVectorizer(stop_words='english')

In [ ]:
x=CV.transform(data['text_clean']).toarray()

In [ ]:
data.head()

,Class,Message,Length,Target,text_clean
0,1,I've been searching for the right words to tha...,196,0,ive been searching for the right words to than...
1,0,Free entry in 2 a wkly comp to win FA Cup fina...,155,1,free entry in 2 a wkly comp to win fa cup fina...
2,1,"Nah I don't think he goes to usf, he lives aro...",61,0,nah i dont think he goes to usf he lives aroun...
3,1,Even my brother is not like to speak with me. ...,77,0,even my brother is not like to speak with me t...
4,1,I HAVE A DATE ON SUNDAY WITH WILL!!!,36,0,i have a date on sunday with will

In [ ]:
xSet = data.text_clean.values
ySet = data.Class.values

ySet

array([1, 0, 1, ..., 1, 1, 1], dtype=object)

In [ ]:
ySet = ySet.astype('int')
ySet

array([1, 0, 1, ..., 1, 1, 1])

In [ ]:
xSet

array(['ive been searching for the right words to thank you for this breather i promise i wont take your help for granted and will fulfil my promise you have been wonderful and a blessing at all times',
       'free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005 text fa to 87121 to receive entry questionstd txt ratetcs apply 08452810075over18s',
       'nah i dont think he goes to usf he lives around here though', ...,
       'pity  was in mood for that soany other suggestions',
       'the guy did some bitching but i acted like id be interested in buying something else next week and he gave it to us for free',
       'rofl its true to its name'], dtype=object)

In [ ]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y = data.Target

In [ ]:
xSet_train,xSet_test,ySet_train,ySet_test = train_test_split(xSet,ySet,test_size=0.25, random_state=10,stratify=ySet)
print(xSet_train.shape,xSet_test.shape)

(4175,) (1392,)

In [ ]:
xSet_train_CV = CV.fit_transform(xSet_train)

In [ ]:
NB=MultinomialNB()
NB.fit(xSet_train_CV,ySet_train)

MultinomialNB()

In [ ]:
# Let's test CV on our test data
xSet_test_CV = CV.transform(xSet_test)

In [ ]:

ySet_predict = NB.predict(xSet_test_CV)
ySet_predict

array([1, 1, 0, ..., 1, 1, 0])

In [ ]:
accuracyScore = accuracy_score(ySet_test,ySet_predict)*100

print("Prediction Accuracy :",accuracyScore)

Prediction Accuracy : 98.49137931034483

In [ ]:
X = data['text_clean'].values
y = data['Class'].values

In [ ]:
y = y.astype('int')

In [ ]:
## text preprocessing and feature vectorizer
# To extract features from a document of words, we import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer


tf=TfidfVectorizer() ## object creation
X=tf.fit_transform(X) ## fitting and transforming the data into vectors

In [ ]:
len(tf.get_feature_names_out())

9537

In [ ]:
X=X.toarray()

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=6)

In [ ]:
from sklearn.naive_bayes import BernoulliNB

## model object creation
nb=BernoulliNB(alpha=0.01)

## fitting the model
nb.fit(X_train,y_train)

## getting the prediction
y_hat=nb.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(classification_report(y_test,y_hat))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96       186
           1       0.99      0.99      0.99      1206

    accuracy                           0.99      1392
   macro avg       0.98      0.98      0.98      1392
weighted avg       0.99      0.99      0.99      1392